### ISSUE TITLE
Suport for Redux-Form v6

### ISSUE THREAD

**Issue by caiobalthazar** [CosticaPuntaru/redux-form-validation#17] opened 2016-08-29 23:26 UTC
Redux-Form v6 is out with some breaking changes to the `Field` data structure.
http://redux-form.com/6.0.1/docs/api/Field.md/
http://redux-form.com/6.0.1/docs/MigrationGuide.md/

I believe some changes in redux-form-validation are required, specially regarding this new `meta` object where the validation errors now reside.

**Comment by CosticaPuntaru** [comment] 2016-09-06 09:43
the redux-form#6 dose a lot of breaking changes,  this module needs a complete rewrite...
The issue is that i don't use this component anymore, i was maintaining it just for the community. 
I'm happy to receive pr's for it or to add other maintainers

**Comment by erin-doyle** [comment] 2016-09-27 15:22
I have been working on a fork of this library to update it to work with redux-form 6.x.  I think it's about ready for a PR for consideration.  There are certainly going to be some changes needed on how FormMessages is used now based on the Field changes.  

I think it might be worth creating a new branch for development of a 0.1.0 or 1.0.0 redux-form-validation version that will have breaking changes for consumers.  That way we can include anything else at this time that might be a breaking change all in one fell swoop.  This could include fixing the Unknown Prop Warning (https://facebook.github.io/react/warnings/unknown-prop.html) now being thrown by the when property in FormMessages children.  That should be opened as a separate issue for us to track but just wanted to point out that there may need to be another breaking change to FormMessages.

**Comment by matanassa** [comment] 2016-10-28 08:09
+1

**Comment by 0xDazzer** [comment] 2016-11-01 09:38
@erin-doyle When are you going to create PR with new changes? Can't wait

**Comment by dziamid** [comment] 2016-12-13 10:41
@CosticaPuntaru since you stopped using this library, maybe you can share with us how you do redux-form validations ATM?

**Comment by CosticaPuntaru** [comment] 2016-12-14 09:55
I no longer work on a project that needs something like redux-form-validations. i no longer work on react. that why i wood like to receive pr's and happy to allow other ppl to work on this library...
My spear time is pretty limited i'm not completely sure when i can work on its update

**Comment by CosticaPuntaru** [comment] 2018-06-17 06:10
i finally got some time to update the library (1.0.0-rc1 (for now)), now supports redux-form 7,

I will close this issue as its solved

**Closed as completed** 2018-06-17 06:10 UTC
